# Created using CreateManifest.ps1 v0.2.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.2.0.json

Identifier: toggle-layers
DisplayName: toggle-layers
Version: "1.40"
ReleaseDate: 2024-06-04
Section: Plugin/other
InstalledSize: 30
Developer:
- sigma-axis
Description: |-
  <enter description here>
  <enter description here>
Website:
- https://github.com/sigma-axis/aviutl_toggle_layers
Files:
- SourceUrl: https://github.com/sigma-axis/aviutl_toggle_layers/releases/download/v1.40/aviutl_toggle_layers-v1.40.zip
  Sha256: aa75964573aa6201e117288149e1994da0597d0c4cbc16fac45d2db81b191e94
  Files:
  - Path: LICENSE
    Sha256: 4268433862d83249d3a1ce152dcf0a0eafaf23d5a57baca379ab675a3894056e
  - Path: README.md
    Sha256: ef58b05226390b5a55a268eae0cd7e71b71c7310dba8e98a71cc546c291a6519
  - Path: toggle_layers.auf
    Sha256: 39196f42d9b903716d25e11c4a0bab00bbe005b0826a4d29090d43cbde5c295d
    Install:
      TargetPath: plugins/toggle_layers.auf
  - Path: toggle_layers.ini
    Sha256: 4d221da0dd7e4e431b717755fdccbdfa1e50e64c549292379129a97dba855b59
    Install:
      TargetPath: plugins/toggle_layers.ini
      ConfFile: true
ManifestVersion: 0.2.0
