# Created using CreateManifest.ps1 v0.2.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.2.0.json

Identifier: toggle-layers
DisplayName: toggle-layers
Version: "1.50"
ReleaseDate: 2024-06-06
Section: Plugin/other
InstalledSize: 32
Developer:
- sigma-axis
Description: |-
  <enter description here>
  <enter description here>
Website:
- https://github.com/sigma-axis/aviutl_toggle_layers
Files:
- SourceUrl: https://github.com/sigma-axis/aviutl_toggle_layers/releases/download/v1.50/aviutl_toggle_layers-v1.50.zip
  Sha256: b84b8dec8407fa503a2f697dcb817c01dcfe300d9c0ee3317c737df5fdce6967
  Files:
  - Path: LICENSE
    Sha256: 4268433862d83249d3a1ce152dcf0a0eafaf23d5a57baca379ab675a3894056e
  - Path: README.md
    Sha256: b4d866545c7a9c79c5de3e04c0d0106d1a456e9dcc9a5f4f63eca6a50e40d7ec
  - Path: toggle_layers.auf
    Sha256: 825310b36c4d2d795d61378cf92e655eba4e22ca71360b71f2da76a0fce89880
    Install:
      TargetPath: plugins/toggle_layers.auf
  - Path: toggle_layers.ini
    Sha256: b04e4db3b403c4c89714f4d102212e4eff6ed4ee0e677d098d859c26e285324c
    Install:
      TargetPath: plugins/toggle_layers.ini
      ConfFile: true
ManifestVersion: 0.2.0
