# Created using CreateManifest.ps1 v0.2.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.2.0.json

Identifier: reactive-dlg
DisplayName: aviutl_reactive_dlg
Version: "1.40"
ReleaseDate: 2024-07-08
Section: plugin/other
InstalledSize: 98
Developer:
- sigma-axis
Description: |-
  <enter description here>
  <enter description here>
Website:
- https://github.com/sigma-axis/aviutl_reactive_dlg
Files:
- SourceUrl: https://github.com/sigma-axis/aviutl_reactive_dlg/releases/download/v1.40/aviutl_reactive_dlg-v1.40.zip
  Sha256: 0fa757b6032de6ead08620d108fb0a183ecb7317ec4008c9652710cbf17ffc05
  Files:
  - Path: LICENSE
    Sha256: 4268433862d83249d3a1ce152dcf0a0eafaf23d5a57baca379ab675a3894056e
  - Path: reactive_dlg.auf
    Sha256: 914278f51e2924a343d942e96f8f59a57567b432293884bbac284a68e6359e78
    Install:
      TargetPath: plugins/reactive_dlg.auf
  - Path: reactive_dlg.ini
    Sha256: db2f23c01694a3b7fcc1e7f4698fb1b16132b6564f46388c5271edf6dcd1d465
    Install:
      TargetPath: plugins/reactive_dlg.ini
      ConfFile: true
  - Path: README.md
    Sha256: f1e95b11b98dc51db36a47432fbd51d4aefebf5f3f0defba529a173739e0296e
ManifestVersion: 0.2.0
