# Created using CreateManifest.ps1 v0.2.0
# yaml-language-server: $schema=https://raw.githubusercontent.com/Per-Terra/butler-pkgs/main/schemas/JSON/manifest/0.2.0.json

Identifier: tl-walkaround
DisplayName: TLショトカ移動
Version: "1.22"
ReleaseDate: 2024-05-01
Section: Plugin/Other
Depends:
- aviutl (= 1.10)
- exedit (= 0.92)
InstalledSize: 52
Developer:
- sigma-axis
Description: |-
  編集点移動のショートカットコマンドを追加するプラグイン
  タイムライン上のオブジェクト境界に移動する，いわゆる編集点移動のショートカットコマンドを追加するプラグインです．他にもスクロール操作などタイムラインをキーボード操作で見て回るのに便利なショートカットコマンドを追加します．
Website:
- https://github.com/sigma-axis/aviutl_tl_walkaround
Files:
- SourceUrl: https://github.com/sigma-axis/aviutl_tl_walkaround/releases/download/v1.22/aviutl_tl_walkaround-v1.22.zip
  Sha256: ee28b11a5996b14c93d482615500a71adeda5ac30411b9b5b94c0fd984599e59
  Files:
  - Path: LICENSE
    Sha256: 4268433862d83249d3a1ce152dcf0a0eafaf23d5a57baca379ab675a3894056e
  - Path: README.md
    Sha256: fa6cb5b16ab19c7a6ea7e06b40e49ae19c8740f0d27d1a9861b58b1e08890aaf
  - Path: tl_walkaround.auf
    Sha256: 7ef40a878cc3c2d697143cdb7eb7ec96f5b979963df0223bb558cd57abdfa760
    Install:
      TargetPath: plugins/tl_walkaround.auf
  - Path: tl_walkaround.ini
    Sha256: 1de47083c617322b74288d2d387c771da0c1b6a33bfc55dcef5dda47d061ddde
    Install:
      TargetPath: plugins/tl_walkaround.ini
      ConfFile: true
ManifestVersion: 0.2.0
